CREATE TABLE AUDITORIA (
DATA DATE,
CPF VARCHAR2(11),
SALARIO_ANTERIOR NUMBER (10,2),
SALARIO_ATUAL NUMBER (10,2),
USUARIO VARCHAR2(40),
PRIMARY KEY (CPF, DATA));
CREATE OR REPLACE TRIGGER alteracao_salario
AFTER DELETE OR INSERT OR UPDATE OF Salario
ON Funcionario
FOR EACH ROW
BEGIN
INSERT INTO Auditoria values(sysdate, :OLD.CPF, :OLD.Salario,
:NEW.Salario, user);
END;
UPDATE Funcionario SET Salario = 55500
WHERE CPF = 88866555576;
SELECT * FROM AUDITORIA;
